apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kroxylicious.fullname" . }}-config
  labels:
    {{- include "kroxylicious.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ include "kroxylicious.config" . | indent 4 }}
{{- if .Values.authorization.enabled }}
  acl-rules.txt: |
{{ .Values.authorization.rules | indent 4 }}
{{- end }}
