apiVersion: v1
kind: Service
metadata:
  name: {{ include "kroxylicious.fullname" . }}
  labels:
    {{- include "kroxylicious.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: proxy
      port: {{ .Values.gateway.port }}
      targetPort: proxy
      protocol: TCP
  selector:
    {{- include "kroxylicious.selectorLabels" . | nindent 4 }}
